INSERT INTO `countries` (`key`, `lang`, `msg_txt`) VALUES
('AU', 'EN', 'Australia'),
('MY', 'EN', 'Malaysia'),
('KR', 'EN', 'Republic of Korea'),
('CN', 'EN', 'China'),
('JP', 'EN', 'Japan'),
('IN', 'EN', 'India'),
('HK', 'EN', 'Hong Kong'),
('TH', 'EN', 'Thailand'),
('VN', 'EN', 'Viet Nam'),
('FR', 'EN', 'France'),
('IT', 'EN', 'Italy'),
('AE', 'EN', 'United Arab Emirates'),
('IL', 'EN', 'Israel'),
('SE', 'EN', 'Sweden'),
('KZ', 'EN', 'Kazakhstan'),
('PT', 'EN', 'Portugal'),
('GR', 'EN', 'Greece'),
('SA', 'EN', 'Saudi Arabia'),
('RU', 'EN', 'Russian Federation'),
('GB', 'EN', 'United Kingdom'),
('DK', 'EN', 'Denmark'),
('BM', 'EN', 'Bermuda'),
('CA', 'EN', 'Canada'),
('PR', 'EN', 'Puerto Rico'),
('VI', 'EN', 'Virgin Islands'),
('BO', 'EN', 'Bolivia'),
('NL', 'EN', 'Netherlands'),
('NZ', 'EN', 'New Zealand'),
('SG', 'EN', 'Singapore'),
('ID', 'EN', 'Indonesia'),
('NP', 'EN', 'Nepal'),
('PH', 'EN', 'Philippines'),
('PG', 'EN', 'Papua New Guinea'),
('PK', 'EN', 'Pakistan'),
('DE', 'EN', 'Germany'),
('CH', 'EN', 'Switzerland'),
('ES', 'EN', 'Spain'),
('BS', 'EN', 'Bahamas'),
('VC', 'EN', 'Saint Vincent and The Grenadines'),
('AR', 'EN', 'Argentina'),
('DM', 'EN', 'Dominica'),
('BD', 'EN', 'Bangladesh'),
('TK', 'EN', 'Tokelau'),
('KH', 'EN', 'Cambodia'),
('MO', 'EN', 'Macao'),
('MV', 'EN', 'Maldives'),
('AF', 'EN', 'Afghanistan'),
('NC', 'EN', 'New Caledonia'),
('FJ', 'EN', 'Fiji'),
('MN', 'EN', 'Mongolia'),
('WF', 'EN', 'Wallis and Futuna'),
('BE', 'EN', 'Belgium'),
('IE', 'EN', 'Ireland'),
('BZ', 'EN', 'Belize'),
('BR', 'EN', 'Brazil'),
('MX', 'EN', 'Mexico'),
('TR', 'EN', 'Turkey'),
('AT', 'EN', 'Austria'),
('PL', 'EN', 'Poland'),
('LV', 'EN', 'Latvia'),
('UA', 'EN', 'Ukraine'),
('IR', 'EN', 'Islamic Republic of Iran'),
('BY', 'EN', 'Belarus'),
('CZ', 'EN', 'Czech Republic'),
('IS', 'EN', 'Iceland'),
('CY', 'EN', 'Cyprus'),
('HU', 'EN', 'Hungary'),
('SK', 'EN', 'Slovakia'),
('MK', 'EN', 'Former Yugoslav Republic of Macedonia'),
('LU', 'EN', 'Luxembourg'),
('NO', 'EN', 'Norway'),
('EE', 'EN', 'Estonia'),
('FI', 'EN', 'Finland'),
('JO', 'EN', 'Jordan'),
('AZ', 'EN', 'Azerbaijan'),
('RS', 'EN', 'Serbia'),
('BG', 'EN', 'Bulgaria'),
('OM', 'EN', 'Oman'),
('RO', 'EN', 'Romania'),
('BH', 'EN', 'Bahrain'),
('GE', 'EN', 'Georgia'),
('SY', 'EN', 'Syrian Arab Republic'),
('MT', 'EN', 'Malta'),
('AM', 'EN', 'Armenia'),
('AL', 'EN', 'Albania'),
('SI', 'EN', 'Slovenia'),
('GU', 'EN', 'Guam'),
('PA', 'EN', 'Panama'),
('BN', 'EN', 'Brunei Darussalam'),
('LK', 'EN', 'Sri Lanka'),
('ME', 'EN', 'Montenegro'),
('NG', 'EN', 'Nigeria'),
('ZW', 'EN', 'Zimbabwe'),
('CI', 'EN', 'Cote D''ivoire'),
('MW', 'EN', 'Malawi'),
('IQ', 'EN', 'Iraq'),
('SD', 'EN', 'Sudan'),
('TJ', 'EN', 'Tajikistan'),
('LB', 'EN', 'Lebanon'),
('MD', 'EN', 'Republic of Moldova'),
('MZ', 'EN', 'Mozambique'),
('CD', 'EN', 'Democratic Republic of The Congo'),
('AO', 'EN', 'Angola'),
('KE', 'EN', 'Kenya'),
('TZ', 'EN', 'United Republic of Tanzania'),
('CG', 'EN', 'Republic of Congo'),
('ZM', 'EN', 'Zambia'),
('BA', 'EN', 'Bosnia and Herzegovina'),
('KW', 'EN', 'Kuwait'),
('LT', 'EN', 'Lithuania'),
('LR', 'EN', 'Liberia'),
('AG', 'EN', 'Antigua and Barbuda'),
('SM', 'EN', 'San Marino'),
('VG', 'EN', 'Virgin Islands'),
('MA', 'EN', 'Morocco'),
('DZ', 'EN', 'Algeria'),
('GM', 'EN', 'Gambia'),
('SZ', 'EN', 'Swaziland'),
('MG', 'EN', 'Madagascar'),
('ZA', 'EN', 'South Africa'),
('FK', 'EN', 'Falkland Islands (malvinas)'),
('UZ', 'EN', 'Uzbekistan'),
('EG', 'EN', 'Egypt'),
('MC', 'EN', 'Monaco'),
('HT', 'EN', 'Haiti'),
('FM', 'EN', 'Federated States of Micronesia'),
('CO', 'EN', 'Colombia'),
('UG', 'EN', 'Uganda'),
('GH', 'EN', 'Ghana'),
('EC', 'EN', 'Ecuador'),
('KY', 'EN', 'Cayman Islands'),
('PE', 'EN', 'Peru'),
('HN', 'EN', 'Honduras'),
('SL', 'EN', 'Sierra Leone'),
('ML', 'EN', 'Mali'),
('NI', 'EN', 'Nicaragua'),
('DO', 'EN', 'Dominican Republic'),
('GD', 'EN', 'Grenada'),
('AN', 'EN', 'Netherlands Antilles'),
('GT', 'EN', 'Guatemala'),
('TT', 'EN', 'Trinidad and Tobago'),
('VE', 'EN', 'Venezuela'),
('CL', 'EN', 'Chile'),
('WS', 'EN', 'Samoa'),
('MH', 'EN', 'Marshall Islands'),
('MP', 'EN', 'Northern Mariana Islands'),
('CR', 'EN', 'Costa Rica'),
('PW', 'EN', 'Palau'),
('BB', 'EN', 'Barbados'),
('LC', 'EN', 'Saint Lucia'),
('SV', 'EN', 'El Salvador'),
('JM', 'EN', 'Jamaica'),
('TC', 'EN', 'Turks and Caicos Islands'),
('VA', 'EN', 'Vatican'),
('PY', 'EN', 'Paraguay'),
('RW', 'EN', 'Rwanda'),
('SR', 'EN', 'Suriname'),
('GY', 'EN', 'Guyana'),
('CM', 'EN', 'Cameroon'),
('KN', 'EN', 'Saint Kitts and Nevis'),
('AW', 'EN', 'Aruba'),
('UY', 'EN', 'Uruguay'),
('NE', 'EN', 'Niger'),
('PM', 'EN', 'Saint Pierre and Miquelon'),
('MF', 'EN', 'Saint Martin'),
('HR', 'EN', 'Croatia'),
('IM', 'EN', 'Isle of Man'),
('BF', 'EN', 'Burkina Faso'),
('BJ', 'EN', 'Benin'),
('GN', 'EN', 'Guinea'),
('BI', 'EN', 'Burundi'),
('JE', 'EN', 'Jersey'),
('SC', 'EN', 'Seychelles'),
('TM', 'EN', 'Turkmenistan'),
('KG', 'EN', 'Kyrgyzstan'),
('GG', 'EN', 'Guernsey'),
('GA', 'EN', 'Gabon'),
('MM', 'EN', 'Myanmar'),
('CF', 'EN', 'Central African Republic'),
('BT', 'EN', 'Bhutan'),
('QA', 'EN', 'Qatar'),
('NA', 'EN', 'Namibia'),
('TD', 'EN', 'Chad'),
('BW', 'EN', 'Botswana'),
('AX', 'EN', 'Finland'),
('RE', 'EN', 'Reunion'),
('MU', 'EN', 'Mauritius'),
('LI', 'EN', 'Liechtenstein'),
('FO', 'EN', 'Faroe Islands'),
('SO', 'EN', 'Somalia'),
('GQ', 'EN', 'Equatorial Guinea'),
('ET', 'EN', 'Ethiopia'),
('SN', 'EN', 'Senegal'),
('TN', 'EN', 'Tunisia'),
('YE', 'EN', 'Yemen'),
('KM', 'EN', 'Comoros'),
('MR', 'EN', 'Mauritania'),
('LY', 'EN', 'Libya'),
('LA', 'EN', 'Lao People''s Democratic Republic'),
('GI', 'EN', 'Gibraltar'),
('MQ', 'EN', 'Martinique'),
('GP', 'EN', 'Guadeloupe'),
('AD', 'EN', 'Andorra'),
('TG', 'EN', 'Togo'),
('AQ', 'EN', 'Antarctica'),
('IO', 'EN', 'British Indian Ocean Territory'),
('CV', 'EN', 'Cape Verde'),
('GL', 'EN', 'Greenland'),
('DJ', 'EN', 'Djibouti'),
('GW', 'EN', 'Guinea-Bissau'),
('LS', 'EN', 'Lesotho'),
('ER', 'EN', 'Eritrea'),
('TV', 'EN', 'Tuvalu'),
('VU', 'EN', 'Vanuatu'),
('PF', 'EN', 'French Polynesia'),
('CU', 'EN', 'Cuba'),
('KP', 'EN', 'Democratic People''s Republic of Korea'),
('TO', 'EN', 'Tonga'),
('TL', 'EN', 'Timor-Leste'),
('UM', 'EN', 'United States Minor Outlying Islands'),
('ST', 'EN', 'Sao Tome and Principe'),
('MS', 'EN', 'Montserrat'),
('TF', 'EN', 'French Southern Territories'),
('GF', 'EN', 'French Guiana'),
('GS', 'EN', 'South Georgia and The South Sandwich Islands'),
('SB', 'EN', 'Solomon Islands'),
('KI', 'EN', 'Kiribati'),
('AS', 'EN', 'American Samoa'),
('NF', 'EN', 'Norfolk Island'),
('NR', 'EN', 'Nauru'),
('AI', 'EN', 'Anguilla'),
('BV', 'EN', 'Bouvet Island'),
('YT', 'EN', 'Mayotte'),
('US', 'EN', 'United States'),
('XX', 'EN', 'Unknown'),
('SS', 'EN', 'South Sudan'),
('AU', 'NL', 'Australia'),
('MY', 'NL', 'Malaysia'),
('KR', 'NL', 'Republic of Korea'),
('CN', 'NL', 'China'),
('JP', 'NL', 'Japan'),
('IN', 'NL', 'India'),
('HK', 'NL', 'Hong Kong'),
('TH', 'NL', 'Thailand'),
('VN', 'NL', 'Viet Nam'),
('FR', 'NL', 'France'),
('IT', 'NL', 'Italy'),
('AE', 'NL', 'United Arab Emirates'),
('IL', 'NL', 'Israel'),
('SE', 'NL', 'Sweden'),
('KZ', 'NL', 'Kazakhstan'),
('PT', 'NL', 'Portugal'),
('GR', 'NL', 'Greece'),
('SA', 'NL', 'Saudi Arabia'),
('RU', 'NL', 'Russian Federation'),
('GB', 'NL', 'United Kingdom'),
('DK', 'NL', 'Denmark'),
('BM', 'NL', 'Bermuda'),
('CA', 'NL', 'Canada'),
('PR', 'NL', 'Puerto Rico'),
('VI', 'NL', 'Virgin Islands'),
('BO', 'NL', 'Bolivia'),
('NL', 'NL', 'Netherlands'),
('NZ', 'NL', 'New Zealand'),
('SG', 'NL', 'Singapore'),
('ID', 'NL', 'Indonesia'),
('NP', 'NL', 'Nepal'),
('PH', 'NL', 'Philippines'),
('PG', 'NL', 'Papua New Guinea'),
('PK', 'NL', 'Pakistan'),
('DE', 'NL', 'Germany'),
('CH', 'NL', 'Switzerland'),
('ES', 'NL', 'Spain'),
('BS', 'NL', 'Bahamas'),
('VC', 'NL', 'Saint Vincent and The Grenadines'),
('AR', 'NL', 'Argentina'),
('DM', 'NL', 'Dominica'),
('BD', 'NL', 'Bangladesh'),
('TK', 'NL', 'Tokelau'),
('KH', 'NL', 'Cambodia'),
('MO', 'NL', 'Macao'),
('MV', 'NL', 'Maldives'),
('AF', 'NL', 'Afghanistan'),
('NC', 'NL', 'New Caledonia'),
('FJ', 'NL', 'Fiji'),
('MN', 'NL', 'Mongolia'),
('WF', 'NL', 'Wallis and Futuna'),
('BE', 'NL', 'Belgium'),
('IE', 'NL', 'Ireland'),
('BZ', 'NL', 'Belize'),
('BR', 'NL', 'Brazil'),
('MX', 'NL', 'Mexico'),
('TR', 'NL', 'Turkey'),
('AT', 'NL', 'Austria'),
('PL', 'NL', 'Poland'),
('LV', 'NL', 'Latvia'),
('UA', 'NL', 'Ukraine'),
('IR', 'NL', 'Islamic Republic of Iran'),
('BY', 'NL', 'Belarus'),
('CZ', 'NL', 'Czech Republic'),
('IS', 'NL', 'Iceland'),
('CY', 'NL', 'Cyprus'),
('HU', 'NL', 'Hungary'),
('SK', 'NL', 'Slovakia'),
('MK', 'NL', 'Former Yugoslav Republic of Macedonia'),
('LU', 'NL', 'Luxembourg'),
('NO', 'NL', 'Norway'),
('EE', 'NL', 'Estonia'),
('FI', 'NL', 'Finland'),
('JO', 'NL', 'Jordan'),
('AZ', 'NL', 'Azerbaijan'),
('RS', 'NL', 'Serbia'),
('BG', 'NL', 'Bulgaria'),
('OM', 'NL', 'Oman'),
('RO', 'NL', 'Romania'),
('BH', 'NL', 'Bahrain'),
('GE', 'NL', 'Georgia'),
('SY', 'NL', 'Syrian Arab Republic'),
('MT', 'NL', 'Malta'),
('AM', 'NL', 'Armenia'),
('AL', 'NL', 'Albania'),
('SI', 'NL', 'Slovenia'),
('GU', 'NL', 'Guam'),
('PA', 'NL', 'Panama'),
('BN', 'NL', 'Brunei Darussalam'),
('LK', 'NL', 'Sri Lanka'),
('ME', 'NL', 'Montenegro'),
('NG', 'NL', 'Nigeria'),
('ZW', 'NL', 'Zimbabwe'),
('CI', 'NL', 'Cote D''ivoire'),
('MW', 'NL', 'Malawi'),
('IQ', 'NL', 'Iraq'),
('SD', 'NL', 'Sudan'),
('TJ', 'NL', 'Tajikistan'),
('LB', 'NL', 'Lebanon'),
('MD', 'NL', 'Republic of Moldova'),
('MZ', 'NL', 'Mozambique'),
('CD', 'NL', 'Democratic Republic of The Congo'),
('AO', 'NL', 'Angola'),
('KE', 'NL', 'Kenya'),
('TZ', 'NL', 'United Republic of Tanzania'),
('CG', 'NL', 'Republic of Congo'),
('ZM', 'NL', 'Zambia'),
('BA', 'NL', 'Bosnia and Herzegovina'),
('KW', 'NL', 'Kuwait'),
('LT', 'NL', 'Lithuania'),
('LR', 'NL', 'Liberia'),
('AG', 'NL', 'Antigua and Barbuda'),
('SM', 'NL', 'San Marino'),
('VG', 'NL', 'Virgin Islands'),
('MA', 'NL', 'Morocco'),
('DZ', 'NL', 'Algeria'),
('GM', 'NL', 'Gambia'),
('SZ', 'NL', 'Swaziland'),
('MG', 'NL', 'Madagascar'),
('ZA', 'NL', 'South Africa'),
('FK', 'NL', 'Falkland Islands (malvinas)'),
('UZ', 'NL', 'Uzbekistan'),
('EG', 'NL', 'Egypt'),
('MC', 'NL', 'Monaco'),
('HT', 'NL', 'Haiti'),
('FM', 'NL', 'Federated States of Micronesia'),
('CO', 'NL', 'Colombia'),
('UG', 'NL', 'Uganda'),
('GH', 'NL', 'Ghana'),
('EC', 'NL', 'Ecuador'),
('KY', 'NL', 'Cayman Islands'),
('PE', 'NL', 'Peru'),
('HN', 'NL', 'Honduras'),
('SL', 'NL', 'Sierra Leone'),
('ML', 'NL', 'Mali'),
('NI', 'NL', 'Nicaragua'),
('DO', 'NL', 'Dominican Republic'),
('GD', 'NL', 'Grenada'),
('AN', 'NL', 'Netherlands Antilles'),
('GT', 'NL', 'Guatemala'),
('TT', 'NL', 'Trinidad and Tobago'),
('VE', 'NL', 'Venezuela'),
('CL', 'NL', 'Chile'),
('WS', 'NL', 'Samoa'),
('MH', 'NL', 'Marshall Islands'),
('MP', 'NL', 'Northern Mariana Islands'),
('CR', 'NL', 'Costa Rica'),
('PW', 'NL', 'Palau'),
('BB', 'NL', 'Barbados'),
('LC', 'NL', 'Saint Lucia'),
('SV', 'NL', 'El Salvador'),
('JM', 'NL', 'Jamaica'),
('TC', 'NL', 'Turks and Caicos Islands'),
('VA', 'NL', 'Vatican'),
('PY', 'NL', 'Paraguay'),
('RW', 'NL', 'Rwanda'),
('SR', 'NL', 'Suriname'),
('GY', 'NL', 'Guyana'),
('CM', 'NL', 'Cameroon'),
('KN', 'NL', 'Saint Kitts and Nevis'),
('AW', 'NL', 'Aruba'),
('UY', 'NL', 'Uruguay'),
('NE', 'NL', 'Niger'),
('PM', 'NL', 'Saint Pierre and Miquelon'),
('MF', 'NL', 'Saint Martin'),
('HR', 'NL', 'Croatia'),
('IM', 'NL', 'Isle of Man'),
('BF', 'NL', 'Burkina Faso'),
('BJ', 'NL', 'Benin'),
('GN', 'NL', 'Guinea'),
('BI', 'NL', 'Burundi'),
('JE', 'NL', 'Jersey'),
('SC', 'NL', 'Seychelles'),
('TM', 'NL', 'Turkmenistan'),
('KG', 'NL', 'Kyrgyzstan'),
('GG', 'NL', 'Guernsey'),
('GA', 'NL', 'Gabon'),
('MM', 'NL', 'Myanmar'),
('CF', 'NL', 'Central African Republic'),
('BT', 'NL', 'Bhutan'),
('QA', 'NL', 'Qatar'),
('NA', 'NL', 'Namibia'),
('TD', 'NL', 'Chad'),
('BW', 'NL', 'Botswana'),
('AX', 'NL', 'Finland'),
('RE', 'NL', 'Reunion'),
('MU', 'NL', 'Mauritius'),
('LI', 'NL', 'Liechtenstein'),
('FO', 'NL', 'Faroe Islands'),
('SO', 'NL', 'Somalia'),
('GQ', 'NL', 'Equatorial Guinea'),
('ET', 'NL', 'Ethiopia'),
('SN', 'NL', 'Senegal'),
('TN', 'NL', 'Tunisia'),
('YE', 'NL', 'Yemen'),
('KM', 'NL', 'Comoros'),
('MR', 'NL', 'Mauritania'),
('LY', 'NL', 'Libya'),
('LA', 'NL', 'Lao People''s Democratic Republic'),
('GI', 'NL', 'Gibraltar'),
('MQ', 'NL', 'Martinique'),
('GP', 'NL', 'Guadeloupe'),
('AD', 'NL', 'Andorra'),
('TG', 'NL', 'Togo'),
('AQ', 'NL', 'Antarctica'),
('IO', 'NL', 'British Indian Ocean Territory'),
('CV', 'NL', 'Cape Verde'),
('GL', 'NL', 'Greenland'),
('DJ', 'NL', 'Djibouti'),
('GW', 'NL', 'Guinea-Bissau'),
('LS', 'NL', 'Lesotho'),
('ER', 'NL', 'Eritrea'),
('TV', 'NL', 'Tuvalu'),
('VU', 'NL', 'Vanuatu'),
('PF', 'NL', 'French Polynesia'),
('CU', 'NL', 'Cuba'),
('KP', 'NL', 'Democratic People''s Republic of Korea'),
('TO', 'NL', 'Tonga'),
('TL', 'NL', 'Timor-Leste'),
('UM', 'NL', 'United States Minor Outlying Islands'),
('ST', 'NL', 'Sao Tome and Principe'),
('MS', 'NL', 'Montserrat'),
('TF', 'NL', 'French Southern Territories'),
('GF', 'NL', 'French Guiana'),
('GS', 'NL', 'South Georgia and The South Sandwich Islands'),
('SB', 'NL', 'Solomon Islands'),
('KI', 'NL', 'Kiribati'),
('AS', 'NL', 'American Samoa'),
('NF', 'NL', 'Norfolk Island'),
('NR', 'NL', 'Nauru'),
('AI', 'NL', 'Anguilla'),
('BV', 'NL', 'Bouvet Island'),
('YT', 'NL', 'Mayotte'),
('US', 'NL', 'United States'),
('XX', 'NL', 'Unknown'),
('SS', 'NL', 'South Sudan'),
('AU', 'FR', 'AUSTRALIE'),
('MY', 'FR', 'MALAISIE'),
('KR', 'FR', 'RÉPUBLIQUE DE CORÉE '),
('CN', 'FR', 'CHINE'),
('JP', 'FR', 'JAPON'),
('IN', 'FR', 'INDE'),
('HK', 'FR', 'HONG KONG'),
('TH', 'FR', 'THAÏLANDE'),
('VN', 'FR', 'VIÊT NAM'),
('FR', 'FR', 'FRANCE'),
('IT', 'FR', 'ITALIE'),
('AE', 'FR', 'ÉMIRATS ARABES UNIS'),
('IL', 'FR', 'ISRAËL'),
('SE', 'FR', 'SUÈDE'),
('KZ', 'FR', 'KAZAKHSTAN'),
('PT', 'FR', 'PORTUGAL'),
('GR', 'FR', 'GRÈCE'),
('SA', 'FR', 'ARABIE SAOUDITE'),
('RU', 'FR', 'FÉDÉRATION DE RUSSIE'),
('GB', 'FR', 'ROYAUME-UNI'),
('DK', 'FR', 'DANEMARK'),
('BM', 'FR', 'BERMUDES'),
('CA', 'FR', 'CANADA'),
('PR', 'FR', 'PORTO RICO'),
('VI', 'FR', 'ÎLES VIERGES'),
('BO', 'FR', 'BOLIVIE'),
('NL', 'FR', 'PAYS-BAS'),
('NZ', 'FR', 'NOUVELLE-ZÉLANDE'),
('SG', 'FR', 'SINGAPOUR'),
('ID', 'FR', 'INDONÉSIE'),
('NP', 'FR', 'NÉPAL'),
('PH', 'FR', 'PHILIPPINES'),
('PG', 'FR', 'PAPOUASIE-NOUVELLE-GUINÉE'),
('PK', 'FR', 'PAKISTAN'),
('DE', 'FR', 'ALLEMAGNE'),
('CH', 'FR', 'SUISSE'),
('ES', 'FR', 'ESPAGNE'),
('BS', 'FR', 'BAHAMAS'),
('VC', 'FR', 'SAINT VINCENT ET LES GRENADINES'),
('AR', 'FR', 'ARGENTINE'),
('DM', 'FR', 'DOMINIQUE'),
('BD', 'FR', 'BANGLADESH'),
('TK', 'FR', 'TOKELAU'),
('KH', 'FR', 'CAMBODGE'),
('MO', 'FR', 'MACAO'),
('MV', 'FR', 'MALDIVES'),
('AF', 'FR', 'AFGHANISTAN'),
('NC', 'FR', 'NOUVELLE-CALÉDONIE'),
('FJ', 'FR', 'FIDJI'),
('MN', 'FR', 'MONGOLIE'),
('WF', 'FR', 'WALLIS ET FUTUNA'),
('BE', 'FR', 'BELGIQUE'),
('IE', 'FR', 'IRLANDE'),
('BZ', 'FR', 'BELIZE'),
('BR', 'FR', 'BRÉSIL'),
('MX', 'FR', 'MEXIQUE'),
('TR', 'FR', 'TURQUIE'),
('AT', 'FR', 'AUTRICHE'),
('PL', 'FR', 'POLOGNE'),
('LV', 'FR', 'LETTONIE'),
('UA', 'FR', 'UKRAINE'),
('IR', 'FR', 'RÉPUBLIQUE ISLAMIQUE D´IRAN'),
('BY', 'FR', 'BIÉLORUSSIE'),
('CZ', 'FR', 'RÉPUBLIQUE TCHÈQUE'),
('IS', 'FR', 'ISLANDE'),
('CY', 'FR', 'CHYPRE'),
('HU', 'FR', 'HONGRIE'),
('SK', 'FR', 'SLOVAQUIE'),
('MK', 'FR', 'ANCIENNE RÉPUBLIQUE YOUGOSLAVE DE MACÉDOINE'),
('LU', 'FR', 'LUXEMBOURG'),
('NO', 'FR', 'NORVÈGE'),
('EE', 'FR', 'ESTONIE'),
('FI', 'FR', 'FINLANDE'),
('JO', 'FR', 'JORDANIE'),
('AZ', 'FR', 'AZERBAÏDJAN'),
('RS', 'FR', 'SERBIE'),
('BG', 'FR', 'BULGARIE'),
('OM', 'FR', 'OMAN'),
('RO', 'FR', 'ROUMANIE'),
('BH', 'FR', 'BAHREÏN'),
('GE', 'FR', 'GÉORGIE'),
('SY', 'FR', 'RÉPUBLIQUE ARABE SYRIENNE'),
('MT', 'FR', 'MALTA'),
('AM', 'FR', 'ARMÉNIE'),
('AL', 'FR', 'ALBANIE'),
('SI', 'FR', 'SLOVÉNIE'),
('GU', 'FR', 'GUAM'),
('PA', 'FR', 'PANAMA'),
('BN', 'FR', 'BRUNEI'),
('LK', 'FR', 'SRI LANKA'),
('ME', 'FR', 'MONTÉNÉGRO'),
('NG', 'FR', 'NIGERIA'),
('ZW', 'FR', 'ZIMBABWE'),
('CI', 'FR', 'COTE D´IVOIRE'),
('MW', 'FR', 'MALAWI'),
('IQ', 'FR', 'IRAK'),
('SD', 'FR', 'SOUDAN'),
('TJ', 'FR', 'TADJIKISTAN'),
('LB', 'FR', 'LIBAN'),
('MD', 'FR', 'RÉPUBLIQUE DE MOLDAVIE'),
('MZ', 'FR', 'MOZAMBIQUE'),
('CD', 'FR', 'RÉPUBLIQUE DÉMOCRATIQUE DU CONGO'),
('AO', 'FR', 'ANGOLA'),
('KE', 'FR', 'KENYA'),
('TZ', 'FR', 'RÉPUBLIQUE UNIE DE TANZANIE'),
('CG', 'FR', 'RÉPUBLIQUE DU CONGO'),
('ZM', 'FR', 'ZAMBIE'),
('BA', 'FR', 'BOSNIE-HERZÉGOVINE'),
('KW', 'FR', 'KOWEÏT'),
('LT', 'FR', 'LITUANIE'),
('LR', 'FR', 'LIBÉRIA'),
('AG', 'FR', 'ANTIGUA ET BARBUDA'),
('SM', 'FR', 'SAINT MARIN'),
('VG', 'FR', 'ÎLES VIERGES'),
('MA', 'FR', 'MAROC'),
('DZ', 'FR', 'ALGÉRIE'),
('GM', 'FR', 'GAMBIE'),
('SZ', 'FR', 'SWAZILAND'),
('MG', 'FR', 'MADAGASCAR'),
('ZA', 'FR', 'AFRIQUE DU SUD'),
('FK', 'FR', 'FALKLAND ISLANDS (ÎLES MALOUINES)'),
('UZ', 'FR', 'OUZBÉKISTAN'),
('EG', 'FR', 'ÉGYPTE'),
('MC', 'FR', 'MONACO'),
('HT', 'FR', 'HAITI'),
('FM', 'FR', 'ÉTATS FÉDÉRÉS DE MICRONÉSIE'),
('CO', 'FR', 'COLOMBIE'),
('UG', 'FR', 'OUGANDA'),
('GH', 'FR', 'GHANA'),
('EC', 'FR', 'ÉQUATEUR'),
('KY', 'FR', 'ÎLES CAÎMANS'),
('PE', 'FR', 'PÉROU'),
('HN', 'FR', 'HONDURAS'),
('SL', 'FR', 'SIERRA LEONE'),
('ML', 'FR', 'MALI'),
('NI', 'FR', 'NICARAGUA'),
('DO', 'FR', 'RÉPUBLIQUE DOMINICAINE'),
('GD', 'FR', 'GRENADE'),
('AN', 'FR', 'ANTILLES NÉERLANDAISES'),
('GT', 'FR', 'GUATEMALA'),
('TT', 'FR', 'TRINITÉ ET TOBAGO'),
('VE', 'FR', 'VENEZUELA'),
('CL', 'FR', 'CHILI'),
('WS', 'FR', 'SAMOA'),
('MH', 'FR', 'ÎLES MARSHALL'),
('MP', 'FR', 'ÎLES MARIANNES DU NORD'),
('CR', 'FR', 'COSTA RICA'),
('PW', 'FR', 'PALAOS'),
('BB', 'FR', 'BARBADE'),
('LC', 'FR', 'SAINTE LUCIE'),
('SV', 'FR', 'SALVADOR'),
('JM', 'FR', 'JAMAÏQUE'),
('TC', 'FR', 'ÎLES TURQUES ET CAÏQUES'),
('VA', 'FR', 'VATICAN'),
('PY', 'FR', 'PARAGUAY'),
('RW', 'FR', 'RWANDA'),
('SR', 'FR', 'SURINAME'),
('GY', 'FR', 'GUYANA'),
('CM', 'FR', 'CAMEROUN'),
('KN', 'FR', 'SAINT CRISTOPHE ET NIÉVÈS'),
('AW', 'FR', 'ARUBA'),
('UY', 'FR', 'URUGUAY'),
('NE', 'FR', 'NIGER'),
('PM', 'FR', 'SAINT PIERRE ET MIQUELON'),
('MF', 'FR', 'SAINT MARTIN'),
('HR', 'FR', 'CROATIE'),
('IM', 'FR', 'ÎLE DE MAN'),
('BF', 'FR', 'BURKINA FASO'),
('BJ', 'FR', 'BÉNIN'),
('GN', 'FR', 'GUINÉE'),
('BI', 'FR', 'BURUNDI'),
('JE', 'FR', 'JERSEY'),
('SC', 'FR', 'SEYCHELLES'),
('TM', 'FR', 'TURKMÉNISTAN'),
('KG', 'FR', 'KIRGHIZISTAN'),
('GG', 'FR', 'GUERNESEY'),
('GA', 'FR', 'GABON'),
('MM', 'FR', 'MYANMAR'),
('CF', 'FR', 'RÉPUBLIQUE CENTRAFRICAINE'),
('BT', 'FR', 'BHOUTAN'),
('QA', 'FR', 'QATAR'),
('NA', 'FR', 'NAMIBIE'),
('TD', 'FR', 'TCHAD'),
('BW', 'FR', 'BOTSWANA'),
('AX', 'FR', 'FINLANDE'),
('RE', 'FR', 'LA RÉUNION'),
('MU', 'FR', 'MAURICE'),
('LI', 'FR', 'LIECHTENSTEIN'),
('FO', 'FR', 'ÎLES FÉROÉ'),
('SO', 'FR', 'SOMALIE'),
('GQ', 'FR', 'GUINÉE ÉQUATORIALE'),
('ET', 'FR', 'ÉTHIOPIE'),
('SN', 'FR', 'SÉNÉGAL'),
('TN', 'FR', 'TUNISIE'),
('YE', 'FR', 'YÉMEN'),
('KM', 'FR', 'COMORES'),
('MR', 'FR', 'MAURITANIE'),
('LY', 'FR', 'LIBYE'),
('LA', 'FR', 'RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE DU LAOS'),
('GI', 'FR', 'GIBRALTAR'),
('MQ', 'FR', 'MARTINIQUE'),
('GP', 'FR', 'GUADELOUPE'),
('AD', 'FR', 'ANDORRE'),
('TG', 'FR', 'TOGO'),
('AQ', 'FR', 'ANTARTIQUE'),
('IO', 'FR', 'TERRITOIRE BRITANNIQUE DE L´OCÉAN INDIEN'),
('CV', 'FR', 'CAP VERT'),
('GL', 'FR', 'GROENLAND'),
('DJ', 'FR', 'DJIBOUTI'),
('GW', 'FR', 'GUINÉE-BISSAU'),
('LS', 'FR', 'LESOTHO'),
('ER', 'FR', 'ÉRYTHRÉE'),
('TV', 'FR', 'TUVALU'),
('VU', 'FR', 'VANUATU'),
('PF', 'FR', 'POLYNÉSIE FRANÇAISE'),
('CU', 'FR', 'CUBA'),
('KP', 'FR', 'RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE CORÉE'),
('TO', 'FR', 'TONGA'),
('TL', 'FR', 'TIMOR ORIENTAL'),
('UM', 'FR', 'ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS'),
('ST', 'FR', 'SAO TOME ET PRINCIPE'),
('MS', 'FR', 'MONTSERRAT'),
('TF', 'FR', 'TERRES AUSTRALES ET ANTARCTIQUES FRANÇAISES'),
('GF', 'FR', 'GUYANE'),
('GS', 'FR', 'GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD'),
('SB', 'FR', 'ÎLES SALOMON'),
('KI', 'FR', 'KIRIBATI'),
('AS', 'FR', 'SAMOA AMÉRICAINES'),
('NF', 'FR', 'ÎLE NORFOLK'),
('NR', 'FR', 'NAURU'),
('AI', 'FR', 'ANGUILLA'),
('BV', 'FR', 'ÎLÉ BOUVET'),
('YT', 'FR', 'MAYOTTE'),
('US', 'FR', 'ÉTATS-UNIS'),
('XX', 'FR', 'INCONNU'),
('SS', 'FR', 'SOUDAN DU SUD'),
('AU', 'DE', 'Australien'),
('MY', 'DE', 'Malaysia'),
('KR', 'DE', 'Korea, Süd'),
('CN', 'DE', 'China'),
('JP', 'DE', 'Japan'),
('IN', 'DE', 'Indien'),
('HK', 'DE', 'Hong Kong'),
('TH', 'DE', 'Thailand'),
('VN', 'DE', 'Vietnam'),
('FR', 'DE', 'Frankreich'),
('IT', 'DE', 'Italien'),
('AE', 'DE', 'Vereinigte Arabische Emirate'),
('IL', 'DE', 'Israel'),
('SE', 'DE', 'Schweden'),
('KZ', 'DE', 'Kasachstan'),
('PT', 'DE', 'Portugal'),
('GR', 'DE', 'Griechenland'),
('SA', 'DE', 'Saudi-Arabien'),
('RU', 'DE', 'Russland'),
('GB', 'DE', 'Großbritannien'),
('DK', 'DE', 'Dänemark'),
('BM', 'DE', 'Bermuda'),
('CA', 'DE', 'Kanada'),
('PR', 'DE', 'Puerto Rico\r\n\r\n'),
('VI', 'DE', 'VIRGIN ISLANDS'),
('BO', 'DE', 'Bolivien'),
('NL', 'DE', 'Niederlande'),
('NZ', 'DE', 'Neuseeland'),
('SG', 'DE', 'Singapur'),
('ID', 'DE', 'Indonesien'),
('NP', 'DE', 'Nepal'),
('PH', 'DE', 'Philippinen'),
('PG', 'DE', 'Papua-Neuguinea'),
('PK', 'DE', 'Pakistan'),
('DE', 'DE', 'Deutschland'),
('CH', 'DE', 'Schweiz'),
('ES', 'DE', 'Spanien'),
('BS', 'DE', 'Bahamas'),
('VC', 'DE', 'Saint Vincent und die Grenadinen'),
('AR', 'DE', 'Argentinien'),
('DM', 'DE', 'Dominica'),
('BD', 'DE', 'Bangladesch'),
('TK', 'DE', 'TOKELAU\n'),
('KH', 'DE', 'Kambodscha'),
('MO', 'DE', 'MACAO\n'),
('MV', 'DE', 'Malediven'),
('AF', 'DE', 'Afghanistan'),
('NC', 'DE', 'NEW CALEDONIA\n'),
('FJ', 'DE', 'Fidschi'),
('MN', 'DE', 'Mongolei'),
('WF', 'DE', 'WALLIS AND FUTUNA\n'),
('BE', 'DE', 'Belgien'),
('IE', 'DE', 'Irland'),
('BZ', 'DE', 'Belize'),
('BR', 'DE', 'Brasilien'),
('MX', 'DE', 'Mexiko'),
('TR', 'DE', 'Türkei'),
('AT', 'DE', 'Österreich'),
('PL', 'DE', 'Polen'),
('LV', 'DE', 'Lettland'),
('UA', 'DE', 'Ukraine'),
('IR', 'DE', 'Iran'),
('BY', 'DE', 'Weißrußland'),
('CZ', 'DE', 'Tschechien.'),
('IS', 'DE', 'Inseln'),
('CY', 'DE', 'Zypern'),
('HU', 'DE', 'Ungarn'),
('SK', 'DE', 'Slowakei'),
('MK', 'DE', 'Mazedonien'),
('LU', 'DE', 'Luxemburg'),
('NO', 'DE', 'Norwegen'),
('EE', 'DE', 'Estland'),
('FI', 'DE', 'Finnland'),
('JO', 'DE', 'Jordanien'),
('AZ', 'DE', 'Aserbaidschan'),
('RS', 'DE', 'Serbien'),
('BG', 'DE', 'Bulgarien'),
('OM', 'DE', 'Oman'),
('RO', 'DE', 'Rumänien'),
('BH', 'DE', 'Bahrain'),
('GE', 'DE', 'Georgien'),
('SY', 'DE', 'Syrien'),
('MT', 'DE', 'Malta'),
('AM', 'DE', 'Armenien'),
('AL', 'DE', 'Albanien'),
('SI', 'DE', 'Slowenien'),
('GU', 'DE', 'GUAM'),
('PA', 'DE', 'Panama'),
('BN', 'DE', 'Brunei'),
('LK', 'DE', 'Sri Lanka'),
('ME', 'DE', 'Montenegro'),
('NG', 'DE', 'Nigeria'),
('ZW', 'DE', 'Simbabwe'),
('CI', 'DE', 'Elfenbeinküste'),
('MW', 'DE', 'Malawi'),
('IQ', 'DE', 'Irak'),
('SD', 'DE', 'Sudan'),
('TJ', 'DE', 'Tadschikistan'),
('LB', 'DE', 'Libanon'),
('MD', 'DE', 'Moldau'),
('MZ', 'DE', 'Mosambik'),
('CD', 'DE', 'D.R. Kongo'),
('AO', 'DE', 'Angola'),
('KE', 'DE', 'Kenya'),
('TZ', 'DE', 'Tansania'),
('CG', 'DE', 'Republik Kongo'),
('ZM', 'DE', 'Sambia'),
('BA', 'DE', 'Bosnien und Herzegovina'),
('KW', 'DE', 'Kuwait '),
('LT', 'DE', 'Litauen'),
('LR', 'DE', 'Liberia'),
('AG', 'DE', 'Antigua und Barbuda'),
('SM', 'DE', 'San Marino'),
('VG', 'DE', 'VIRGIN ISLANDS'),
('MA', 'DE', 'Marokko'),
('DZ', 'DE', 'Algerien'),
('GM', 'DE', 'Gambia'),
('SZ', 'DE', 'Swasiland'),
('MG', 'DE', 'Madagaskar'),
('ZA', 'DE', 'Südafrika'),
('FK', 'DE', 'FALKLAND ISLANDS (MALVINAS)\n'),
('UZ', 'DE', 'Usbekistan'),
('EG', 'DE', 'Ägypten'),
('MC', 'DE', 'Monaco'),
('HT', 'DE', 'Haiti'),
('FM', 'DE', 'Mikronesien'),
('CO', 'DE', 'Kolumbien'),
('UG', 'DE', 'Uganda'),
('GH', 'DE', 'Ghana'),
('EC', 'DE', 'Ecuador'),
('KY', 'DE', 'CAYMAN ISLANDS\n'),
('PE', 'DE', 'Peru'),
('HN', 'DE', 'Honduras'),
('SL', 'DE', 'Sierra Leone'),
('ML', 'DE', 'Mali'),
('NI', 'DE', 'Nicaragua'),
('DO', 'DE', 'Dominikanische Republik'),
('GD', 'DE', 'Grenada'),
('AN', 'DE', 'NETHERLANDS ANTILLES'),
('GT', 'DE', 'Guatemala'),
('TT', 'DE', 'Trinidad und Tobago'),
('VE', 'DE', 'Venezuela'),
('CL', 'DE', 'Chile'),
('WS', 'DE', 'Samoa'),
('MH', 'DE', 'Republik Marshallinseln'),
('MP', 'DE', 'NORTHERN MARIANA ISLANDS\n'),
('CR', 'DE', 'Costa Rica'),
('PW', 'DE', 'Palau'),
('BB', 'DE', 'Barbados'),
('LC', 'DE', 'Saint Lucia'),
('SV', 'DE', 'El Salvador'),
('JM', 'DE', 'Jamaika'),
('TC', 'DE', 'TURKS AND CAICOS ISLANDS\n'),
('VA', 'DE', 'Vatikan'),
('PY', 'DE', 'Paraguay'),
('RW', 'DE', 'Ruanda'),
('SR', 'DE', 'Suriname'),
('GY', 'DE', 'Guyana'),
('CM', 'DE', 'Kamerun'),
('KN', 'DE', 'Saint Kitts und Nevis'),
('AW', 'DE', 'ARUBA\n'),
('UY', 'DE', 'Uruguay'),
('NE', 'DE', 'Niger'),
('PM', 'DE', 'SAINT PIERRE AND MIQUELON\n'),
('MF', 'DE', 'SAINT MARTIN\n'),
('HR', 'DE', 'Kroatien'),
('IM', 'DE', 'ISLE OF MAN\n'),
('BF', 'DE', 'Burkina Faso'),
('BJ', 'DE', 'Benin'),
('GN', 'DE', 'Guinea'),
('BI', 'DE', 'Burundi'),
('JE', 'DE', 'JERSEY\n'),
('SC', 'DE', 'Seychellen'),
('TM', 'DE', 'Turkmenistan'),
('KG', 'DE', 'Kirgisistan'),
('GG', 'DE', 'GUERNSEY'),
('GA', 'DE', 'Gabun'),
('MM', 'DE', 'Myanmar (Burma)'),
('CF', 'DE', 'Zentralafrikanische Republik'),
('BT', 'DE', 'Bhutan'),
('QA', 'DE', 'Katar'),
('NA', 'DE', 'Namibia'),
('TD', 'DE', 'Tschad'),
('BW', 'DE', 'Botswana'),
('AX', 'DE', 'FINLAND\n'),
('RE', 'DE', 'REUNION'),
('MU', 'DE', 'Mauritius'),
('LI', 'DE', 'Liechtenstein'),
('FO', 'DE', 'FAROE ISLANDS\n'),
('SO', 'DE', 'Somalia'),
('GQ', 'DE', 'Äquatorialguinea'),
('ET', 'DE', 'Äthiopien'),
('SN', 'DE', 'Senegal'),
('TN', 'DE', 'Tunesien'),
('YE', 'DE', 'Jemen'),
('KM', 'DE', 'Komoren'),
('MR', 'DE', 'Mauretanien'),
('LY', 'DE', 'Libyen'),
('LA', 'DE', 'Laos'),
('GI', 'DE', 'GIBRALTAR\n'),
('MQ', 'DE', 'MARTINIQUE\n'),
('GP', 'DE', 'GUADELOUPE\n'),
('AD', 'DE', 'Andorra'),
('TG', 'DE', 'Togo'),
('AQ', 'DE', 'ANTARCTICA\n'),
('IO', 'DE', 'BRITISH INDIAN OCEAN TERRITORY\n'),
('CV', 'DE', 'Kap Verde'),
('GL', 'DE', 'GREENLAND\n'),
('DJ', 'DE', 'Dschibuti'),
('GW', 'DE', 'Guinea-Bissau'),
('LS', 'DE', 'Lesotho'),
('ER', 'DE', 'Eritrea'),
('TV', 'DE', 'Tuvalu'),
('VU', 'DE', 'Vanuatu'),
('PF', 'DE', 'FRENCH POLYNESIA\n'),
('CU', 'DE', 'Kuba'),
('KP', 'DE', 'Korea, Nord'),
('TO', 'DE', 'Tonga'),
('TL', 'DE', 'Timor Leste'),
('UM', 'DE', 'UNITED STATES MINOR OUTLYING ISLANDS\n'),
('ST', 'DE', 'São Tomé und Príncipe'),
('MS', 'DE', 'MONTSERRAT'),
('TF', 'DE', 'FRENCH SOUTHERN TERRITORIES\n'),
('GF', 'DE', 'FRENCH GUIANA\n'),
('GS', 'DE', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS\n'),
('SB', 'DE', 'Salomonen'),
('KI', 'DE', 'Republik Kiribati'),
('AS', 'DE', 'American Samoa\n'),
('NF', 'DE', 'NORFOLK ISLAND\n'),
('NR', 'DE', 'Nauru'),
('AI', 'DE', 'ANGUILLA\n'),
('BV', 'DE', 'BOUVET ISLAND\n'),
('YT', 'DE', 'MAYOTTE\n'),
('US', 'DE', 'Vereinigte Staaten'),
('XX', 'DE', 'Unknown'),
('SS', 'DE', 'Süd Sudan');
