-- phpMyAdmin SQL Dump
-- version 4.0.10.14
-- http://www.phpmyadmin.net
--
-- Host: localhost:3306
-- Generation Time: Oct 24, 2016 at 03:49 PM
-- Server version: 5.5.52-cll
-- PHP Version: 5.6.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `evelocit_1id`
--

--
-- Dumping data for table `screen`
--

INSERT INTO `screen` (`id`, `parent`, `name`, `label`, `slug`, `template`, `class`, `identifier`, `sort`, `created_at`, `updated_at`, `status`, `help_label`, `help_video_url`, `help_html`) VALUES
('2', '', '1iD Home', 'MyID_dashboard', 'dashboard', 'render-full-screen', NULL, 'page-dashboard', 1, NULL, '2016-10-23 13:59:20', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'Thank you for being part of the 1iD Network!\nUsing animated movies (by web-page) we try to help you finding your way through our 1iD solution.\n\nOn this page we have grouped all short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28)'),
('57f3c031c3518', '2', 'Personal Data', 'personal_data', 'personal-data', 'Personal Data', NULL, NULL, 1, '2016-10-03 20:00:00', '2016-10-21 12:25:11', 1, NULL, 'https://www.youtube.com/watch?v=yCJinBQvYj0', 'In your Personal Data you enter your data once.\n\nYour Personal Data is divided in different sections:\n1/ General Data: Name, Birthday, Blood Group, Logon Language, Picture\n2/ Contact Data: Address, E-mail, Phone Number(s)\n3/ Passwords: 1iD Password\n4/ Security Settings: \n     a/ What you share with users & companies\n     b/ How you want to protect your 1iD: level of security by information or action\n5/ Bank Accounts: Your connected bank accounts and paypall user\n6/ Biography Data: Here you can enter your entire Biography\n\nThis is just Prototype V1.0 so let us know if something is not working or if you have any suggestions or questions.\n\nThanks,\n1iD Team'),
('57fcc759a2ca0', '57f3c031c3518', 'General Data', 'general_data', 'general-data', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:04:57', '2016-10-22 16:32:44', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcc7e7cadc3', '57f3c031c3518', 'My Contact Data', 'my_contact_data', 'my-contact-data', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:07:19', '2016-10-22 16:33:49', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcc7fe505f2', '57f3c031c3518', 'Password Data', 'password_data', 'password-data', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:07:42', '2016-10-22 16:34:13', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcc81c8548b', '57f3c031c3518', 'Security Settings', 'security_settings', 'security-settings', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:08:12', '2016-10-22 16:34:50', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcc8600e990', '57fcc81c8548b', 'What I Share', 'what_i_share', 'what-i-share', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:09:20', '2016-10-22 16:35:09', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcc8bbd69c4', '', 'MyID Access Security', 'MyID_access_security', 'my-id-access-security', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:10:51', '2016-10-22 16:36:25', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcc8f1d895d', '57f3c031c3518', 'Bank Account Data', 'bank_account', 'bank-account-data', 'Bank Account Data', NULL, NULL, 1, '2016-10-11 09:11:45', '2016-10-22 16:36:41', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fccaba33921', '57fe20431baa5', 'Experience', 'biography:_work_exp', 'biography/work-experience', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:19:22', '2016-10-21 12:47:19', 1, NULL, 'https://www.youtube.com/watch?v=r-0aaRtaf90', 'Update your Biography Data once and use it in different areas:\n1/ Biography Generator (Prototype V1.0 works!)\n2/ Connected Agencies (To be integrated)\n3/ Job Postings (To be integrated)\n\nThe Biography Data is divided in different (connected sections):\n1/ Work Experience\n2/ Projects\n3/ Education\n4/ Languages\n5/ Interests\n6/ Qualifications\n7/ References\n\nThis is just Prototype V1.0 so let us know if something is not working or if you have any suggestions or questions.\nThe Prototype is working but we will for sure improve without touching your data.\n\nThanks,\n1iD Team'),
('57fccad9904b4', '57fe20431baa5', 'Projects', 'biography:_projects', 'biography/projects', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:19:53', '2016-10-21 12:47:34', 1, NULL, 'https://www.youtube.com/watch?v=r-0aaRtaf90', 'Update your Biography Data once and use it in different areas:\n1/ Biography Generator (Prototype V1.0 works!)\n2/ Connected Agencies (To be integrated)\n3/ Job Postings (To be integrated)\n\nThe Biography Data is divided in different (connected sections):\n1/ Work Experience\n2/ Projects\n3/ Education\n4/ Languages\n5/ Interests\n6/ Qualifications\n7/ References\n\nThis is just Prototype V1.0 so let us know if something is not working or if you have any suggestions or questions.\nThe Prototype is working but we will for sure improve without touching your data.\n\nThanks,\n1iD Team'),
('57fccaefb306f', '57fe20431baa5', 'Education', 'biography:_education', 'biography/education', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:20:15', '2016-10-21 12:47:45', 1, NULL, 'https://www.youtube.com/watch?v=r-0aaRtaf90', 'Update your Biography Data once and use it in different areas:\n1/ Biography Generator (Prototype V1.0 works!)\n2/ Connected Agencies (To be integrated)\n3/ Job Postings (To be integrated)\n\nThe Biography Data is divided in different (connected sections):\n1/ Work Experience\n2/ Projects\n3/ Education\n4/ Languages\n5/ Interests\n6/ Qualifications\n7/ References\n\nThis is just Prototype V1.0 so let us know if something is not working or if you have any suggestions or questions.\nThe Prototype is working but we will for sure improve without touching your data.\n\nThanks,\n1iD Team'),
('57fccb056c490', '57fe20431baa5', 'Languages', 'biography:_languages', 'biography/languages', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:20:37', '2016-10-21 12:47:56', 1, NULL, 'https://www.youtube.com/watch?v=r-0aaRtaf90', 'Update your Biography Data once and use it in different areas:\n1/ Biography Generator (Prototype V1.0 works!)\n2/ Connected Agencies (To be integrated)\n3/ Job Postings (To be integrated)\n\nThe Biography Data is divided in different (connected sections):\n1/ Work Experience\n2/ Projects\n3/ Education\n4/ Languages\n5/ Interests\n6/ Qualifications\n7/ References\n\nThis is just Prototype V1.0 so let us know if something is not working or if you have any suggestions or questions.\nThe Prototype is working but we will for sure improve without touching your data.\n\nThanks,\n1iD Team'),
('57fccb17086ee', '57fe20431baa5', 'Interests', 'biography:_interests', 'biography/interests', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:20:55', '2016-10-21 12:48:08', 1, NULL, 'https://www.youtube.com/watch?v=r-0aaRtaf90', 'Update your Biography Data once and use it in different areas:\n1/ Biography Generator (Prototype V1.0 works!)\n2/ Connected Agencies (To be integrated)\n3/ Job Postings (To be integrated)\n\nThe Biography Data is divided in different (connected sections):\n1/ Work Experience\n2/ Projects\n3/ Education\n4/ Languages\n5/ Interests\n6/ Qualifications\n7/ References\n\nThis is just Prototype V1.0 so let us know if something is not working or if you have any suggestions or questions.\nThe Prototype is working but we will for sure improve without touching your data.\n\nThanks,\n1iD Team'),
('57fccb2650e99', '57fe20431baa5', 'Qualifications', 'biography:_qualifications', 'biography/qualifications', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:21:10', '2016-10-21 12:48:18', 1, NULL, 'https://www.youtube.com/watch?v=r-0aaRtaf90', 'Update your Biography Data once and use it in different areas:\n1/ Biography Generator (Prototype V1.0 works!)\n2/ Connected Agencies (To be integrated)\n3/ Job Postings (To be integrated)\n\nThe Biography Data is divided in different (connected sections):\n1/ Work Experience\n2/ Projects\n3/ Education\n4/ Languages\n5/ Interests\n6/ Qualifications\n7/ References\n\nThis is just Prototype V1.0 so let us know if something is not working or if you have any suggestions or questions.\nThe Prototype is working but we will for sure improve without touching your data.\n\nThanks,\n1iD Team'),
('57fccb38758b0', '57fe20431baa5', 'References', 'biography:_references', 'biography/references', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:21:28', '2016-10-21 12:48:29', 1, NULL, 'https://www.youtube.com/watch?v=r-0aaRtaf90', 'Update your Biography Data once and use it in different areas:\n1/ Biography Generator (Prototype V1.0 works!)\n2/ Connected Agencies (To be integrated)\n3/ Job Postings (To be integrated)\n\nThe Biography Data is divided in different (connected sections):\n1/ Work Experience\n2/ Projects\n3/ Education\n4/ Languages\n5/ Interests\n6/ Qualifications\n7/ References\n\nThis is just Prototype V1.0 so let us know if something is not working or if you have any suggestions or questions.\nThe Prototype is working but we will for sure improve without touching your data.\n\nThanks,\n1iD Team'),
('57fccc000bafe', '2', 'Contacts', 'contacts', 'contacts', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:24:48', '2016-10-20 09:00:34', 1, NULL, 'https://www.youtube.com/watch?v=O5zF1-rRm4U', 'Play video to get help with this page.'),
('57fccc385fb9d', '57fccc000bafe', 'Contacts Data', 'contacts_data', 'contacts-data', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:25:44', '2016-10-20 09:01:33', 1, NULL, 'https://www.youtube.com/watch?v=O5zF1-rRm4U', 'Play video to get help with this page.'),
('57fcd0058925b', '2', 'Loyalty Cards', 'loyalty_cards', 'loyalty-cards', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:41:57', '2016-10-20 08:59:41', 1, NULL, 'https://www.youtube.com/watch?v=4vr8Igg0jp8', 'Play video to get help with this page.'),
('57fcd013ca49b', '2', 'Reading List', 'reading_list', 'reading-list', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:42:11', '2016-10-20 08:58:58', 1, NULL, 'https://www.youtube.com/watch?v=Euk39dy0nXM', 'Play video to get help with this page.'),
('57fcd07f0878f', '2', 'Saved Passwords', 'saved_passwords', 'saved-passwords', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:43:59', '2016-10-22 16:37:05', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd0b67b42b', '2', 'Send Information', 'send_information', 'send-information', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:44:54', '2016-10-22 16:37:22', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd0d467e73', '2', 'Task List', 'task_list', 'task-list', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:45:24', '2016-10-22 16:37:40', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd0e0cca99', '2', 'Calendar', 'calendar', 'calendar', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:45:36', '2016-10-22 16:38:00', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd11655c7e', '2', 'File Server', 'file_server', 'file-server', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:46:30', '2016-10-22 16:38:29', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd24eac2c7', '2', 'Resume Generator', 'resume_generation', 'resume-generator', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:51:42', '2016-10-24 09:00:02', 1, NULL, 'https://www.youtube.com/watch?v=0x9xMHDvxhU&list=PLdoPUFh1z3oJhlE_I6wAceHdPh0MXuDwc', 'Using 1iD placeholders you can generate your Biography in any template you want!\nKeep your Biography Data up-to-date and generate your CV in no-time.\nCV Builder (with help & placeholders) > Create Template > Upload Template and generate CV!'),
('57fcd36c322f1', '2', 'i-Payment', 'i_payment', 'i-payment', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:56:28', '2016-10-22 16:38:50', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd38bb116c', '57fcd36c322f1', 'i-Pay detail', 'i_pay_detail', 'i-pay-detail', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:56:59', '2016-10-22 16:39:11', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd3af2821f', '57fcd36c322f1', 'i-Pay Invoice Handling', 'i_pay_invoices', 'i-pay-invoice-handling', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:57:35', '2016-10-22 16:39:39', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd3c459beb', '57fcd36c322f1', 'i-Pay Monitor', '', 'i-pay-monitor', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:57:56', '2016-10-22 16:40:07', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd3f5237e9', '57fcd36c322f1', 'i-Pay History', 'i_pay_history', 'i-pay-history', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:58:45', '2016-10-22 16:40:30', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fcd40f5859d', '2', '1iD Dashboard', 'myid_dashboard', 'my-id-dashboard', 'render-full-screen', NULL, NULL, 1, '2016-10-11 09:59:11', '2016-10-24 08:25:04', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('57fe20431baa5', '57f3c031c3518', 'Biography Data', 'biography', 'biography-data-hub', 'render-full-screen', NULL, 'page-dashboard', 1, '2016-10-12 09:36:35', '2016-10-21 12:46:29', 1, NULL, 'https://www.youtube.com/watch?v=r-0aaRtaf90', 'Update your Biography Data once and use it in different areas:\n1/ Biography Generator (Prototype V1.0 works!)\n2/ Connected Agencies (To be integrated)\n3/ Job Postings (To be integrated)\n\nThe Biography Data is divided in different (connected sections):\n1/ Work Experience\n2/ Projects\n3/ Education\n4/ Languages\n5/ Interests\n6/ Qualifications\n7/ References\n\nThis is just Prototype V1.0 so let us know if something is not working or if you have any suggestions or questions.\nThe Prototype is working but we will for sure improve without touching your data.\n\nThanks,\n1iD Team'),
('58008625d7cf4', '2', 'Solutions', '1id_access_security', 'solutions', 'render-full-screen', NULL, 'page-dashboard', 1, '2016-10-14 05:15:49', '2016-10-22 16:41:20', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('58061da1ce072', '2', 'Companies', 'companies', 'companies', 'render-full-screen', NULL, NULL, 1, '2016-10-18 11:03:29', '2016-10-24 07:09:32', 1, NULL, 'https://www.youtube.com/watch?v=ZYCk-dgsCFE&list=PLdoPUFh1z3oJ9pF21oVi2aSCZZ-oaWY8H', 'This page has no detailed help yet so in the meantime we have grouped all existing short movies together.\n\nIn order to keep it simple we have kept all movies short (30-60s) an have structured all movies in the same way:\n1/ Section Information\n2/ Prototype v1.0\n3/ Future Plans\n\nOnly the 1iD Concept Introduction has a different structure and is a little bit longer (02:28).'),
('580dd06c1ff4b', '58061da1ce072', 'Companies View', 'view_companies', 'companies/view', 'render-full-screen', NULL, NULL, 1, '2016-10-24 07:12:12', '2016-10-24 07:20:42', 1, NULL, NULL, NULL),
('580dd0970257b', '58061da1ce072', 'Search Companies', 'search_companies', 'companies/search-companies', 'render-full-screen', NULL, NULL, 1, '2016-10-24 07:12:55', '2016-10-24 07:20:06', 1, NULL, NULL, NULL),
('580dd0a85398e', '58061da1ce072', 'My Companies', 'my_companies', 'companies/my', 'render-full-screen', NULL, NULL, 1, '2016-10-24 07:13:12', '2016-10-24 07:21:18', 1, NULL, NULL, NULL);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
